In [46]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 200)

In [57]:
df_westjet = pd.read_excel('WestJet Data 4-12-22.xlsx')

In [60]:
print(df_westjet.info())
print(df_westjet.shape)
print(df_westjet.shape[0])
print(df_westjet.describe())
print(df_westjet.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 327804 entries, 0 to 327803
Columns: 103 entries, Date to Overall Experience 6 Product
dtypes: float64(93), int64(1), object(9)
memory usage: 257.6+ MB
None
(327804, 103)
327804
         Guest Count  Arrivals 3 Service  Arrivals 6 Product  \
count  327804.000000         8376.000000        24033.000000
mean        1.371496            8.507999            8.897183
std         0.691005            2.386416            1.914459
min         1.000000            0.000000            0.000000
25%         1.000000            8.000000            8.000000
50%         1.000000            9.000000           10.000000
75%         2.000000           10.000000           10.000000
max        10.000000           10.000000           10.000000

       Arrivals 5 Service  Arrivals 4 Product  Arrivals 2 Product  \
count        24033.000000        16332.000000        16332.000000
mean             8.589065            8.103662            8.824455
std              1.845046            2.578075            1.816614
min              0.000000            0.000000            0.000000
25%              8.000000            7.000000            8.000000
50%              9.000000            9.000000           10.000000
75%             10.000000           10.000000           10.000000
max             10.000000           10.000000           10.000000

         Arrivals 1  Checkin 4 Service  Checkin 3 Service  Checkin 5 Product  \
count  24033.000000        5559.000000       40082.000000       32964.000000
mean       8.312612           8.867782           9.050447           8.661328
std        2.363028           2.201598           1.788441           2.151605
min        0.000000           0.000000           0.000000           0.000000
25%        8.000000           9.000000           9.000000           8.000000
50%        9.000000          10.000000          10.000000          10.000000
75%       10.000000          10.000000          10.000000          10.000000
max       10.000000          10.000000          10.000000          10.000000

       Checkin 2 Product  Checkin Kiosk 1 Product  Checkin Kiosk 4 Service  \
count        5559.000000              4617.000000               2032.00000
mean            8.572405                 8.856400                  8.43061
std             2.464524                 1.887418                  2.50044
min             0.000000                 0.000000                  0.00000
25%             8.000000                 8.000000                  8.00000
50%            10.000000                10.000000                 10.00000
75%            10.000000                10.000000                 10.00000
max            10.000000                10.000000                 10.00000

       Checkin Kiosk 2 Product  Checkin Kiosk 3 Product  \
count              4617.000000              4617.000000
mean                  8.392679                 8.391813
std                   2.315229                 2.214955
min                   0.000000                 0.000000
25%                   8.000000                 8.000000
50%                   9.000000                 9.000000
75%                  10.000000                10.000000
max                  10.000000                10.000000

       Checkin Mobile 2 Product  Checkin Mobile 1 Product     Checkin 1  \
count              30919.000000              30919.000000  60711.000000
mean                   8.969663                  8.882596      8.701520
std                    1.659726                  1.781119      2.141942
min                    0.000000                  0.000000      0.000000
25%                    8.000000                  8.000000      8.000000
50%                   10.000000                 10.000000     10.000000
75%                   10.000000                 10.000000     10.000000
max                   10.000000                 10.000000     10.000000

       Checkin Web 2 Product  Checkin Web 1 Product  Checkin 6 Service  \
count           19616.000000           19616.000000        2492.000000
mean                8.742302               8.673175           8.782905
std                 1.872352               1.972429           2.025683
min                 0.000000               0.000000           0.000000
25%                 8.000000               8.000000           8.000000
50%                 9.000000               9.000000          10.000000
75%                10.000000              10.000000          10.000000
max                10.000000              10.000000          10.000000

       Departures 7 Service  Departures 6 Service  Departures 3 Service  \
count           31423.00000          81352.000000          81352.000000
mean                8.86408              8.558204              8.935244
std                 1.81057              2.027258              1.685463
min                 0.00000              0.000000              0.000000
25%                 8.00000              8.000000              8.000000
50%                10.00000              9.000000             10.000000
75%                10.00000             10.000000             10.000000
max                10.00000             10.000000             10.000000

       Departures 4 Service  Departures 8 Product  Departures 2 Product  \
count          81352.000000          31423.000000          81352.000000
mean               8.709718              8.349935              8.217745
std                1.902809              2.169597              2.089881
min                0.000000              0.000000              0.000000
25%                8.000000              8.000000              7.000000
50%                9.000000              9.000000              9.000000
75%               10.000000             10.000000             10.000000
max               10.000000             10.000000             10.000000

       Departures 5 Service  Departures 1  Lounge FB 1  Lounge amenities 2  \
count          81352.000000  81352.000000          0.0                 0.0
mean               8.688231      8.422645          NaN                 NaN
std                1.980525      2.238316          NaN                 NaN
min                0.000000      0.000000          NaN                 NaN
25%                8.000000      8.000000          NaN                 NaN
50%                9.000000      9.000000          NaN                 NaN
75%               10.000000     10.000000          NaN                 NaN
max               10.000000     10.000000          NaN                 NaN

       Lounge amenities 3  Lounge amenities 4  Lounge service 5  \
count                 0.0                 0.0               0.0
mean                  NaN                 NaN               NaN
std                   NaN                 NaN               NaN
min                   NaN                 NaN               NaN
25%                   NaN                 NaN               NaN
50%                   NaN                 NaN               NaN
75%                   NaN                 NaN               NaN
max                   NaN                 NaN               NaN

       Lounge entry experience 6  Lounge entry experience 7  Lounge service 8  \
count                        0.0                        0.0               0.0
mean                         NaN                        NaN               NaN
std                          NaN                        NaN               NaN
min                          NaN                        NaN               NaN
25%                          NaN                        NaN               NaN
50%                          NaN                        NaN               NaN
75%                          NaN                        NaN               NaN
max                          NaN                        NaN               NaN

       Lounge FB 9  Lounge service 10  Lounge entry experience 11  \
count          0.0                0.0                         0.0
mean           NaN                NaN                         NaN
std            NaN                NaN                         NaN
min            NaN                NaN                         NaN
25%            NaN                NaN                         NaN
50%            NaN                NaN                         NaN
75%            NaN                NaN                         NaN
max            NaN                NaN                         NaN

       Lounge facility 12  Lounge facility 13  Lounge facility 14  \
count                 0.0                 0.0                 0.0
mean                  NaN                 NaN                 NaN
std                   NaN                 NaN                 NaN
min                   NaN                 NaN                 NaN
25%                   NaN                 NaN                 NaN
50%                   NaN                 NaN                 NaN
75%                   NaN                 NaN                 NaN
max                   NaN                 NaN                 NaN

       Lounge facility 15  Lounge service 16  Lounge FB 17  \
count                 0.0                0.0           0.0
mean                  NaN                NaN           NaN
std                   NaN                NaN           NaN
min                   NaN                NaN           NaN
25%                   NaN                NaN           NaN
50%                   NaN                NaN           NaN
75%                   NaN                NaN           NaN
max                   NaN                NaN           NaN

       Lounge amenities 18  Lounge FB 19  Lounge facility 20  Lounge FB 21  \
count                  0.0           0.0                 0.0           0.0
mean                   NaN           NaN                 NaN           NaN
std                    NaN           NaN                 NaN           NaN
min                    NaN           NaN                 NaN           NaN
25%                    NaN           NaN                 NaN           NaN
50%                    NaN           NaN                 NaN           NaN
75%                    NaN           NaN                 NaN           NaN
max                    NaN           NaN                 NaN           NaN

       Lounge FB 22  Lounge FB 23  Lounge service 24  Lounge service 25  \
count           0.0           0.0                0.0                0.0
mean            NaN           NaN                NaN                NaN
std             NaN           NaN                NaN                NaN
min             NaN           NaN                NaN                NaN
25%             NaN           NaN                NaN                NaN
50%             NaN           NaN                NaN                NaN
75%             NaN           NaN                NaN                NaN
max             NaN           NaN                NaN                NaN

       Lounge service 26  Lounge service 27  Lounge service 28  \
count                0.0                0.0                0.0
mean                 NaN                NaN                NaN
std                  NaN                NaN                NaN
min                  NaN                NaN                NaN
25%                  NaN                NaN                NaN
50%                  NaN                NaN                NaN
75%                  NaN                NaN                NaN
max                  NaN                NaN                NaN

       Lounge service 29  Lounges 0  Overall Experience  \
count                0.0        0.0        86876.000000
mean                 NaN        NaN            8.002705
std                  NaN        NaN            2.635209
min                  NaN        NaN            0.000000
25%                  NaN        NaN            7.000000
50%                  NaN        NaN            9.000000
75%                  NaN        NaN           10.000000
max                  NaN        NaN           10.000000

       Connections 2 Product  Connections 3 Product  Connections 4 Service  \
count                    0.0                    0.0                    0.0
mean                     NaN                    NaN                    NaN
std                      NaN                    NaN                    NaN
min                      NaN                    NaN                    NaN
25%                      NaN                    NaN                    NaN
50%                      NaN                    NaN                    NaN
75%                      NaN                    NaN                    NaN
max                      NaN                    NaN                    NaN

       Connections 5 Product  Connections 6 Product  Connections 7 Product  \
count                    0.0                    0.0                    0.0
mean                     NaN                    NaN                    NaN
std                      NaN                    NaN                    NaN
min                      NaN                    NaN                    NaN
25%                      NaN                    NaN                    NaN
50%                      NaN                    NaN                    NaN
75%                      NaN                    NaN                    NaN
max                      NaN                    NaN                    NaN

       Connections 8 Service  Connections 1  Inflight 1 Product  \
count                    0.0            0.0         6006.000000
mean                     NaN            NaN            7.956876
std                      NaN            NaN            2.217703
min                      NaN            NaN            0.000000
25%                      NaN            NaN            7.000000
50%                      NaN            NaN            8.000000
75%                      NaN            NaN           10.000000
max                      NaN            NaN           10.000000

       Inflight 2 Product  Inflight 3 Service  Inflight 4 Service  \
count        74832.000000         4848.000000         5335.000000
mean             7.607801            8.313944            8.664667
std              2.358492            2.824127            2.562642
min              0.000000            0.000000            0.000000
25%              7.000000            8.000000            9.000000
50%              8.000000           10.000000           10.000000
75%             10.000000           10.000000           10.000000
max             10.000000           10.000000           10.000000

       Inflight 5 Service  Inflight 6 Service  Inflight 7 Service  \
count         5400.000000          5400.00000         5394.000000
mean             8.761111             8.95037            8.817204
std              2.487004             2.28562            2.401162
min              0.000000             0.00000            0.000000
25%              9.000000             9.00000            9.000000
50%             10.000000            10.00000           10.000000
75%             10.000000            10.00000           10.000000
max             10.000000            10.00000           10.000000

       Inflight 8 Service  Inflight 9 FB  Inflight 10 FB  Inflight 11 FB  \
count        74832.000000    5050.000000    74832.000000     5052.000000
mean             8.779974       7.801782        7.184640        4.814331
std              1.787319       2.748902        2.640004        3.274236
min              0.000000       0.000000        0.000000        0.000000
25%              8.000000       7.000000        6.000000        2.000000
50%              9.000000       9.000000        8.000000        5.000000
75%             10.000000      10.000000        9.000000        8.000000
max             10.000000      10.000000       10.000000       10.000000

       Inflight 12 Product  Inflight 13 Product  Inflight 14 Product  \
count          1944.000000          3283.000000          6035.000000
mean              5.928498             7.681694             6.224524
std               3.922372             2.446027             3.234734
min               0.000000             0.000000             0.000000
25%               1.000000             7.000000             4.000000
50%               7.000000             8.000000             7.000000
75%              10.000000            10.000000             9.000000
max              10.000000            10.000000            10.000000

       Inflight 15 Product   Inflight 16  Inflight 17 FB  Inflight 18 FB  \
count          5954.000000  74832.000000     4906.000000     4871.000000
mean              8.080114      8.155629        5.697921        5.932663
std               2.012008      2.282156        3.240616        3.321571
min               0.000000      0.000000        0.000000        0.000000
25%               7.000000      7.000000        3.000000        3.000000
50%               8.000000      9.000000        6.000000        7.000000
75%              10.000000     10.000000        8.000000        9.000000
max              10.000000     10.000000       10.000000       10.000000

       Inflight 19 Product  Inflight 20 Product  Purpose of travel  \
count          6038.000000           527.000000                0.0
mean              5.664790             8.931689                NaN
std               3.170165             1.857848                NaN
min               0.000000             0.000000                NaN
25%               3.000000             8.500000                NaN
50%               6.000000            10.000000                NaN
75%               8.000000            10.000000                NaN
max              10.000000            10.000000                NaN

       Overall Experience 2  Overall Experience 3 Service  \
count          86876.000000                  86876.000000
mean               7.244935                      7.905670
std                2.826292                      2.622989
min                0.000000                      0.000000
25%                6.000000                      7.000000
50%                8.000000                      9.000000
75%               10.000000                     10.000000
max               10.000000                     10.000000

       Overall Experience 4 Product  Overall Experience 5 Product  \
count                  86876.000000                  86876.000000
mean                       7.632465                      7.390004
std                        2.679359                      2.782444
min                        0.000000                      0.000000
25%                        7.000000                      6.000000
50%                        8.000000                      8.000000
75%                       10.000000                     10.000000
max                       10.000000                     10.000000

       Overall Experience 6 Product
count                  86876.000000
mean                       7.233010
std                        2.712491
min                        0.000000
25%                        6.000000
50%                        8.000000
75%                       10.000000
max                       10.000000

Date                                 0
Route                                0
Checked bags                         0
Children                             0
Connection                           0
Guest Count                          0
LFBucket                             0
OTPArrivalBucket                     0
OTPDepBucket                         0
Survey                               0
Arrivals 3 Service              319428
Arrivals 6 Product              303771
Arrivals 5 Service              303771
Arrivals 4 Product              311472
Arrivals 2 Product              311472
Arrivals 1                      303771
Checkin 4 Service               322245
Checkin 3 Service               287722
Checkin 5 Product               294840
Checkin 2 Product               322245
Checkin Kiosk 1 Product         323187
Checkin Kiosk 4 Service         325772
Checkin Kiosk 2 Product         323187
Checkin Kiosk 3 Product         323187
Checkin Mobile 2 Product        296885
Checkin Mobile 1 Product        296885
Checkin 1                       267093
Checkin Web 2 Product           308188
Checkin Web 1 Product           308188
Checkin 6 Service               325312
Departures 7 Service            296381
Departures 6 Service            246452
Departures 3 Service            246452
Departures 4 Service            246452
Departures 8 Product            296381
Departures 2 Product            246452
Departures 5 Service            246452
Departures 1                    246452
Lounge FB 1                     327804
Lounge amenities 2              327804
Lounge amenities 3              327804
Lounge amenities 4              327804
Lounge service 5                327804
Lounge entry experience 6       327804
Lounge entry experience 7       327804
Lounge service 8                327804
Lounge FB 9                     327804
Lounge service 10               327804
Lounge entry experience 11      327804
Lounge facility 12              327804
Lounge facility 13              327804
Lounge facility 14              327804
Lounge facility 15              327804
Lounge service 16               327804
Lounge FB 17                    327804
Lounge amenities 18             327804
Lounge FB 19                    327804
Lounge facility 20              327804
Lounge FB 21                    327804
Lounge FB 22                    327804
Lounge FB 23                    327804
Lounge service 24               327804
Lounge service 25               327804
Lounge service 26               327804
Lounge service 27               327804
Lounge service 28               327804
Lounge service 29               327804
Lounges 0                       327804
Overall Experience              240928
Connections 2 Product           327804
Connections 3 Product           327804
Connections 4 Service           327804
Connections 5 Product           327804
Connections 6 Product           327804
Connections 7 Product           327804
Connections 8 Service           327804
Connections 1                   327804
Inflight 1 Product              321798
Inflight 2 Product              252972
Inflight 3 Service              322956
Inflight 4 Service              322469
Inflight 5 Service              322404
Inflight 6 Service              322404
Inflight 7 Service              322410
Inflight 8 Service              252972
Inflight 9 FB                   322754
Inflight 10 FB                  252972
Inflight 11 FB                  322752
Inflight 12 Product             325860
Inflight 13 Product             324521
Inflight 14 Product             321769
Inflight 15 Product             321850
Inflight 16                     252972
Inflight 17 FB                  322898
Inflight 18 FB                  322933
Inflight 19 Product             321766
Inflight 20 Product             327277
Purpose of travel               327804
Overall Experience 2            240928
Overall Experience 3 Service    240928
Overall Experience 4 Product    240928
Overall Experience 5 Product    240928
Overall Experience 6 Product    240928
dtype: int64

### Remove Empty Columns and Duplicate Rows

In [48]:
empty_cols = [col for col in df_westjet.columns if df_westjet[col].isnull().all()]
df_westjet.drop(empty_cols,axis=1,inplace=True)
df_westjet.drop_duplicates(keep = 'first', inplace = True, ignore_index = True)

### Change Column Format and Clean data

In [71]:
df_westjet.Date = pd.to_datetime(df_westjet.Date)
df_westjet.OTPArrivalBucket = df_westjet.OTPArrivalBucket.str.replace('min','').str.strip()
df_westjet.OTPArrivalBucket = df_westjet.OTPArrivalBucket.str.replace(' to ','-')
df_westjet.OTPArrivalBucket = df_westjet.OTPArrivalBucket.str.replace('More than 5 hours','300')
df_westjet.OTPArrivalBucket = df_westjet.OTPArrivalBucket.str.replace('Null',"")
df_westjet.OTPArrivalBucket = df_westjet.OTPArrivalBucket.str.replace('Early',"")
df_westjet.OTPDepBucket = df_westjet.OTPDepBucket.str.replace('min','').str.strip()
df_westjet.OTPDepBucket = df_westjet.OTPDepBucket.str.replace(' to ','-')
df_westjet.OTPDepBucket = df_westjet.OTPDepBucket.str.replace('More than 5 hours','300')
df_westjet.LFBucket = df_westjet.LFBucket.str.replace(' to ','-')

In [54]:
df_metadata = pd.read_excel('Field explanations .xlsx')
df_metadata

### Export clean data to Speadsheet

In [78]:
df_westjet

,Date,Route,Checked bags,Children,Connection,Guest Count,LFBucket,OTPArrivalBucket,OTPDepBucket,Survey,Arrivals 3 Service,Arrivals 6 Product,Arrivals 5 Service,Arrivals 4 Product,Arrivals 2 Product,Arrivals 1,Checkin 4 Service,Checkin 3 Service,Checkin 5 Product,Checkin 2 Product,Checkin Kiosk 1 Product,Checkin Kiosk 4 Service,Checkin Kiosk 2 Product,Checkin Kiosk 3 Product,Checkin Mobile 2 Product,Checkin Mobile 1 Product,Checkin 1,Checkin Web 2 Product,Checkin Web 1 Product,Checkin 6 Service,Departures 7 Service,Departures 6 Service,Departures 3 Service,Departures 4 Service,Departures 8 Product,Departures 2 Product,Departures 5 Service,Departures 1,Lounge FB 1,Lounge amenities 2,Lounge amenities 3,Lounge amenities 4,Lounge service 5,Lounge entry experience 6,Lounge entry experience 7,Lounge service 8,Lounge FB 9,Lounge service 10,Lounge entry experience 11,Lounge facility 12,Lounge facility 13,Lounge facility 14,Lounge facility 15,Lounge service 16,Lounge FB 17,Lounge amenities 18,Lounge FB 19,Lounge facility 20,Lounge FB 21,Lounge FB 22,Lounge FB 23,Lounge service 24,Lounge service 25,Lounge service 26,Lounge service 27,Lounge service 28,Lounge service 29,Lounges 0,Overall Experience,Connections 2 Product,Connections 3 Product,Connections 4 Service,Connections 5 Product,Connections 6 Product,Connections 7 Product,Connections 8 Service,Connections 1,Inflight 1 Product,Inflight 2 Product,Inflight 3 Service,Inflight 4 Service,Inflight 5 Service,Inflight 6 Service,Inflight 7 Service,Inflight 8 Service,Inflight 9 FB,Inflight 10 FB,Inflight 11 FB,Inflight 12 Product,Inflight 13 Product,Inflight 14 Product,Inflight 15 Product,Inflight 16,Inflight 17 FB,Inflight 18 FB,Inflight 19 Product,Inflight 20 Product,Purpose of travel,Overall Experience 2,Overall Experience 3 Service,Overall Experience 4 Product,Overall Experience 5 Product,Overall Experience 6 Product
0,2018-01-01,JMZZBS,Y,N,Y,1,0-49,91-120,61-75,Departures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,10.0,NaN,10.0,10.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-01-08,JMZZBS,Y,N,Y,1,0-49,181-240,181-240,Departures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,10.0,NaN,10.0,10.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2018-01-14,JMZZBS,Y,N,Y,2,0-49,61-75,61-75,Departures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,3.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2018-02-05,JMZZBS,Y,N,Y,1,0-49,16-30,31-45,Departures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,10.0,NaN,10.0,10.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018-02-26,JMZZBS,Y,N,Y,1,0-49,Early,Early,Departures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,10.0,2.0,NaN,2.0,10.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327799,2019-12-19,QOOIEK,N,N,Y,2,0-49,Early,Early,Inflight,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,10.0,NaN,8.0,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
327800,2019-12-20,QOOIEK,N,N,Y,1,0-49,Early,Early,Overall Experience,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,10.0,8.0,9.0,7.0
327801,2019-12-22,QOOIEK,Y,N,Y,3,0-49,Early,0-15,Inflight,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,9.0,NaN,5.0,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
327802,2019-12-27,QOOIEK,Y,N,Y,3,0-49,Early,Early,Inflight,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,10.0,NaN,10.0,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
327803,2019-12-29,QOOIEK,Y,N,Y,1,0-49,Early,0-15,Check-in,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_westjet.to_excel('westjetDataClean.xlsx', index = False)